title: Lorem ipsum dolor sit amet, consectetur adipiscing elit
author: AtticusYong
email: atticusy28965@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello everyone! I am Atticus Yong and I started coding a few months or years ago. I started coding first with Python.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
